import { Type, type Static } from "@sinclair/typebox";
import {
  CommandAcceptedEventSchema,
  CommandRejectedEventSchema,
} from "./audit-events.js";
import {
  CheckResolvedEventSchema,
  PhysicalRollCancelledEventSchema,
  PhysicalRollRequestedEventSchema,
  SparkRestoredByCompensationEventSchema,
  SparkSpentEventSchema,
} from "./checks.js";
import {
  ActionSlotSpentEventSchema,
  ActionSlotRestoredEventSchema,
  ActivationStartedEventSchema,
  ActorMovedEventSchema,
  BossOverlayActivatedEventSchema,
  CharacterDiedEventSchema,
  CombatActionPendingEventSchema,
  CombatResolvedEventSchema,
  CombatStartedEventSchema,
  DeathTestAidAppliedEventSchema,
  DeathTestPendingEventSchema,
  EnemyActionSelectedEventSchema,
  HeroStabilizedEventSchema,
  ImpactAppliedEventSchema,
  ObjectiveAdvancedEventSchema,
  PermanentScarGainedEventSchema,
  ReactionWindowClosedEventSchema,
  ReactionWindowOpenedEventSchema,
  ReactionRestoredEventSchema,
  RoundAdvancedEventSchema,
  WoundMarkedEventSchema,
} from "./domains/combat.js";
import {
  ChallengeCheckPendingEventSchema,
  ChallengeResolvedEventSchema,
  ChallengeStartedEventSchema,
  ChallengeTracksChangedEventSchema,
} from "./domains/challenges.js";
import {
  CharacterMaterializedEventSchema,
  ConditionAppliedEventSchema,
  ConditionRemovedEventSchema,
  CostlyRestCompletedEventSchema,
  RankAdvancedEventSchema,
  ResourceChangedEventSchema,
  SceneResourcesResetEventSchema,
  SceneAbilityUsedEventSchema,
  SignificantGearSpentEventSchema,
  SparkRecoveredEventSchema,
} from "./domains/playable-characters.js";
import {
  RitualContributionEventSchema,
  RitualCheckPendingEventSchema,
  RitualInterruptedEventSchema,
  RitualReadyEventSchema,
  RitualResolvedEventSchema,
  RitualStartedEventSchema,
} from "./domains/rituals.js";
import {
  LeverageCreatedEventSchema,
  LeverageSpentEventSchema,
  SocialStanceChangedEventSchema,
  SocialCheckPendingEventSchema,
  SocialStateEstablishedEventSchema,
} from "./domains/social.js";
import { TransactionCompensatedEventSchema } from "./undo.js";

export const GameEventSchema = Type.Union([
  CommandAcceptedEventSchema,
  CommandRejectedEventSchema,
  CheckResolvedEventSchema,
  PhysicalRollCancelledEventSchema,
  PhysicalRollRequestedEventSchema,
  SparkSpentEventSchema,
  SparkRestoredByCompensationEventSchema,
  CharacterMaterializedEventSchema,
  SignificantGearSpentEventSchema,
  ResourceChangedEventSchema,
  SparkRecoveredEventSchema,
  CostlyRestCompletedEventSchema,
  SceneResourcesResetEventSchema,
  RankAdvancedEventSchema,
  SceneAbilityUsedEventSchema,
  ConditionAppliedEventSchema,
  ConditionRemovedEventSchema,
  CombatStartedEventSchema,
  ActivationStartedEventSchema,
  ActionSlotSpentEventSchema,
  ActionSlotRestoredEventSchema,
  ActorMovedEventSchema,
  EnemyActionSelectedEventSchema,
  CombatActionPendingEventSchema,
  DeathTestPendingEventSchema,
  ImpactAppliedEventSchema,
  WoundMarkedEventSchema,
  ReactionWindowOpenedEventSchema,
  ReactionWindowClosedEventSchema,
  ReactionRestoredEventSchema,
  RoundAdvancedEventSchema,
  BossOverlayActivatedEventSchema,
  ObjectiveAdvancedEventSchema,
  DeathTestAidAppliedEventSchema,
  HeroStabilizedEventSchema,
  PermanentScarGainedEventSchema,
  CharacterDiedEventSchema,
  CombatResolvedEventSchema,
  ChallengeStartedEventSchema,
  ChallengeCheckPendingEventSchema,
  ChallengeTracksChangedEventSchema,
  ChallengeResolvedEventSchema,
  SocialStateEstablishedEventSchema,
  SocialCheckPendingEventSchema,
  SocialStanceChangedEventSchema,
  LeverageCreatedEventSchema,
  LeverageSpentEventSchema,
  RitualStartedEventSchema,
  RitualCheckPendingEventSchema,
  RitualContributionEventSchema,
  RitualReadyEventSchema,
  RitualResolvedEventSchema,
  RitualInterruptedEventSchema,
  TransactionCompensatedEventSchema,
]);

export type GameEvent = Static<typeof GameEventSchema>;
