import type { GuidedBeat } from "@lldm/contracts";

const beat = (value: GuidedBeat): GuidedBeat => Object.freeze(value);

const continueTo = (to: GuidedBeat["beat_id"]): GuidedBeat["transitions"] => [
  { on: "continue", to },
];

export const FLOODGATE_GUIDED_BEATS: readonly GuidedBeat[] = Object.freeze([
  beat({
    beat_id: "guided_beat_opening_001",
    revision: 1,
    kind: "opening",
    visibility: "public",
    public_text:
      "Rain drums on the sealed Floodgate while a warning bell sounds from inside. The lower ward has minutes before the channel rises.",
    options: [
      {
        option_id: "guided_option_enter_controls_001",
        label: "Enter through the controls",
        stakes: "Faster access, but the gate mechanism may wake.",
      },
      {
        option_id: "guided_option_cross_spillway_001",
        label: "Cross the spillway",
        stakes: "A safer mechanism route, but the flood gains ground.",
      },
    ],
    operation: { kind: "room_choice" },
    transitions: [
      {
        on: "selected_option",
        option_id: "guided_option_enter_controls_001",
        to: "guided_beat_clue_mara_001",
      },
      {
        on: "selected_option",
        option_id: "guided_option_cross_spillway_001",
        to: "guided_beat_clue_mara_001",
      },
    ],
    checkpoint: true,
    declared_merge: false,
    terminal_conclusion: null,
    recent_summary: "The party chose a way into the Floodgate.",
    tv_mode: "choice",
  }),
  beat({
    beat_id: "guided_beat_clue_mara_001",
    revision: 1,
    kind: "private_clue",
    visibility: "seat_private",
    addressed_seat_id: "seat_mara_001",
    public_text: "Each hero notices a different sign in the old works.",
    private_text:
      "The strain lines point away from the main gate: opening the upper relief first will keep the stonework standing.",
    options: [],
    operation: { kind: "deliver_private_clue" },
    transitions: continueTo("guided_beat_clue_sable_001"),
    checkpoint: false,
    declared_merge: false,
    terminal_conclusion: null,
    recent_summary: "Mara received a private observation.",
    tv_mode: "scene",
  }),
  beat({
    beat_id: "guided_beat_clue_sable_001",
    revision: 1,
    kind: "private_clue",
    visibility: "seat_private",
    addressed_seat_id: "seat_sable_001",
    public_text: "The Floodgate offers more than one route.",
    private_text:
      "A dry chalk trace marks a maintenance crawl from the spillway to the pump gallery; it bypasses the jammed lower door.",
    options: [],
    operation: { kind: "deliver_private_clue" },
    transitions: continueTo("guided_beat_clue_ilyra_001"),
    checkpoint: false,
    declared_merge: false,
    terminal_conclusion: null,
    recent_summary: "Sable received a private observation.",
    tv_mode: "scene",
  }),
  beat({
    beat_id: "guided_beat_clue_ilyra_001",
    revision: 1,
    kind: "private_clue",
    visibility: "seat_private",
    addressed_seat_id: "seat_ilyra_001",
    public_text: "Old civic marks remain under the spray.",
    private_text:
      "The custodian's seal promises safe passage to anyone carrying a ward accord; the bell chime is the proper signal, not a threat.",
    options: [],
    operation: { kind: "deliver_private_clue" },
    transitions: continueTo("guided_beat_clue_oren_001"),
    checkpoint: false,
    declared_merge: false,
    terminal_conclusion: null,
    recent_summary: "Ilyra received a private observation.",
    tv_mode: "scene",
  }),
  beat({
    beat_id: "guided_beat_clue_oren_001",
    revision: 1,
    kind: "private_clue",
    visibility: "seat_private",
    addressed_seat_id: "seat_oren_001",
    public_text: "A pale current moves behind the gate lamps.",
    private_text:
      "The ritual circuit is not broken; it is reversed. A prepared wick at the west socket can turn the current without feeding it more power.",
    options: [],
    operation: { kind: "deliver_private_clue" },
    transitions: continueTo("guided_beat_clue_kest_001"),
    checkpoint: false,
    declared_merge: false,
    terminal_conclusion: null,
    recent_summary: "Oren received a private observation.",
    tv_mode: "scene",
  }),
  beat({
    beat_id: "guided_beat_clue_kest_001",
    revision: 1,
    kind: "private_clue",
    visibility: "seat_private",
    addressed_seat_id: "seat_kest_001",
    public_text: "The machinery repeats with a dangerous rhythm.",
    private_text:
      "The locking pawl lifts for one breath after every third bell strike. That is the only clean opening across the gear floor.",
    options: [],
    operation: { kind: "deliver_private_clue" },
    transitions: continueTo("guided_beat_clue_nima_001"),
    checkpoint: false,
    declared_merge: false,
    terminal_conclusion: null,
    recent_summary: "Kest received a private observation.",
    tv_mode: "scene",
  }),
  beat({
    beat_id: "guided_beat_clue_nima_001",
    revision: 1,
    kind: "private_clue",
    visibility: "seat_private",
    addressed_seat_id: "seat_nima_001",
    public_text: "Voices echo below the bell chamber.",
    private_text:
      "The trapped ward crew answers the old work cadence. If someone calls it clearly, they can turn the relief wheel together.",
    options: [],
    operation: { kind: "deliver_private_clue" },
    transitions: continueTo("guided_beat_optional_spark_001"),
    checkpoint: false,
    declared_merge: false,
    terminal_conclusion: null,
    recent_summary: "Nima received a private observation.",
    tv_mode: "scene",
  }),
  beat({
    beat_id: "guided_beat_optional_spark_001",
    revision: 1,
    kind: "optional_spark",
    visibility: "public",
    public_text:
      "The first crossing can be tested quietly, or one hero may spend Spark to roll the pivotal approach in hand.",
    options: [],
    operation: { kind: "resolve_check", physical: false, spark_eligible: true },
    transitions: continueTo("guided_beat_challenge_001"),
    checkpoint: false,
    declared_merge: false,
    terminal_conclusion: null,
    recent_summary: "The party chose whether to invoke Spark.",
    tv_mode: "scene",
  }),
  beat({
    beat_id: "guided_beat_challenge_001",
    revision: 1,
    kind: "challenge",
    visibility: "public",
    public_text:
      "Reach the relief controls before the lower channel overtops. Progress and Danger both move with every committed approach.",
    options: [
      {
        option_id: "guided_option_challenge_route_001",
        label: "Find the maintenance route",
        stakes: "Progress through position; failure closes the dry path.",
      },
      {
        option_id: "guided_option_challenge_brace_001",
        label: "Brace and force the controls",
        stakes: "Direct progress; failure drives water into the gallery.",
      },
    ],
    operation: {
      kind: "start_challenge",
      definition_id: "content_challenge_floodgate_sequence_001",
    },
    transitions: [
      { on: "Crisis", to: "guided_beat_cost_merge_001" },
      { on: "Setback", to: "guided_beat_cost_merge_001" },
      { on: "Success", to: "guided_beat_social_001" },
      { on: "Triumph", to: "guided_beat_social_001" },
    ],
    checkpoint: false,
    declared_merge: false,
    terminal_conclusion: null,
    recent_summary: "The approach changed Progress and Danger.",
    tv_mode: "choice",
  }),
  beat({
    beat_id: "guided_beat_cost_merge_001",
    revision: 1,
    kind: "merge",
    visibility: "public",
    public_text:
      "The party reaches the inner works, but the failed approach leaves the lower causeway flooding behind them.",
    options: [],
    operation: { kind: "scene_transition" },
    transitions: continueTo("guided_beat_social_001"),
    checkpoint: true,
    declared_merge: true,
    terminal_conclusion: null,
    recent_summary: "Failure advanced the story with a declared flood cost.",
    tv_mode: "scene",
  }),
  beat({
    beat_id: "guided_beat_social_001",
    revision: 1,
    kind: "social",
    visibility: "public",
    public_text:
      "Warden Pell bars the bell stair. She fears that opening the relief will abandon the crew below, and she will not trade their lives for speed.",
    options: [],
    operation: {
      kind: "establish_social",
      definition_id: "content_social_gatewarden_nera_001",
    },
    transitions: [
      { on: "Crisis", to: "guided_beat_ritual_001" },
      { on: "Setback", to: "guided_beat_ritual_001" },
      { on: "Success", to: "guided_beat_ritual_001" },
      { on: "Triumph", to: "guided_beat_ritual_001" },
    ],
    checkpoint: false,
    declared_merge: true,
    terminal_conclusion: null,
    recent_summary:
      "The exchange with Warden Pell changed the party's leverage.",
    tv_mode: "scene",
  }),
  beat({
    beat_id: "guided_beat_ritual_001",
    revision: 1,
    kind: "ritual",
    visibility: "public",
    public_text:
      "The reversed current can wake the relief mechanism. The ritual requires a prepared wick and one Supply; interruption preserves anything already paid.",
    options: [
      {
        option_id: "guided_option_ritual_reverse_001",
        label: "Reverse the current",
        stakes: "Spend the declared requirements to steady the relief.",
      },
      {
        option_id: "guided_option_ritual_ground_001",
        label: "Ground it through the bell",
        stakes: "Preserve the controls, but draw the custodian's attention.",
      },
    ],
    operation: {
      kind: "start_ritual",
      definition_id: "content_ritual_floodgate_relief_001",
    },
    transitions: [
      { on: "Crisis", to: "guided_beat_combat_001" },
      { on: "Setback", to: "guided_beat_combat_001" },
      { on: "Success", to: "guided_beat_combat_001" },
      { on: "Triumph", to: "guided_beat_combat_001" },
      { on: "cost", to: "guided_beat_combat_001" },
    ],
    checkpoint: true,
    declared_merge: true,
    terminal_conclusion: null,
    recent_summary:
      "The ritual changed the relief mechanism at a visible cost.",
    tv_mode: "choice",
  }),
  beat({
    beat_id: "guided_beat_combat_001",
    revision: 1,
    kind: "combat",
    visibility: "public",
    public_text:
      "The Bellmaw Custodian wakes across the five named zones. Open the spillway objective before the chamber is lost.",
    options: [],
    operation: { kind: "start_combat", variant_key: "party_3" },
    transitions: [
      { on: "combat_victory", to: "guided_beat_physical_001" },
      { on: "withdrawal", to: "guided_beat_conclusion_withdrawal_001" },
      { on: "defeat", to: "guided_beat_conclusion_defeat_001" },
    ],
    checkpoint: false,
    declared_merge: false,
    terminal_conclusion: null,
    recent_summary: "The Floodgate tactical encounter reached an outcome.",
    tv_mode: "map",
  }),
  beat({
    beat_id: "guided_beat_physical_001",
    revision: 1,
    kind: "mandatory_physical",
    visibility: "public",
    public_text:
      "With the spillway moving, one hero must set the final locking tooth before the surge arrives. The complete target, modifiers, face outcomes, and stakes are visible before the die is entered.",
    options: [],
    operation: { kind: "resolve_check", physical: true, spark_eligible: false },
    transitions: [
      { on: "Crisis", to: "guided_beat_conclusion_cost_001" },
      { on: "Setback", to: "guided_beat_conclusion_cost_001" },
      { on: "Success", to: "guided_beat_conclusion_success_001" },
      { on: "Triumph", to: "guided_beat_conclusion_success_001" },
    ],
    checkpoint: true,
    declared_merge: false,
    terminal_conclusion: null,
    recent_summary:
      "A disclosed physical d20 settled the Floodgate's final lock.",
    tv_mode: "physical_roll",
  }),
  beat({
    beat_id: "guided_beat_conclusion_success_001",
    revision: 1,
    kind: "conclusion",
    visibility: "public",
    public_text:
      "The relief opens cleanly. The lower ward drains beneath a steady bell, and the crew walks out together.",
    options: [],
    operation: { kind: "conclude" },
    transitions: [],
    checkpoint: true,
    declared_merge: false,
    terminal_conclusion: "clean_success",
    recent_summary: "The Floodgate ended in a clean success.",
    tv_mode: "conclusion",
  }),
  beat({
    beat_id: "guided_beat_conclusion_cost_001",
    revision: 1,
    kind: "conclusion",
    visibility: "public",
    public_text:
      "The relief catches after the surge tears through the pump gallery. The ward is saved, but its old works will not serve again without rebuilding.",
    options: [],
    operation: { kind: "conclude" },
    transitions: [],
    checkpoint: true,
    declared_merge: false,
    terminal_conclusion: "success_with_cost",
    recent_summary: "The Floodgate ended in success with a lasting cost.",
    tv_mode: "conclusion",
  }),
  beat({
    beat_id: "guided_beat_conclusion_withdrawal_001",
    revision: 1,
    kind: "conclusion",
    visibility: "public",
    public_text:
      "The party withdraws with the trapped crew while the lower ward floods. Everyone lives, but the Floodgate remains in the custodian's grasp.",
    options: [],
    operation: { kind: "conclude" },
    transitions: [],
    checkpoint: true,
    declared_merge: false,
    terminal_conclusion: "withdrawal",
    recent_summary: "The party secured a retreat conclusion.",
    tv_mode: "conclusion",
  }),
  beat({
    beat_id: "guided_beat_conclusion_defeat_001",
    revision: 1,
    kind: "conclusion",
    visibility: "public",
    public_text:
      "The chamber is lost and the relief stays shut. The survivors reach high ground as the lower ward becomes a dark new channel.",
    options: [],
    operation: { kind: "conclude" },
    transitions: [],
    checkpoint: true,
    declared_merge: false,
    terminal_conclusion: "defeat",
    recent_summary: "The Floodgate ended in defeat without resetting history.",
    tv_mode: "conclusion",
  }),
]);
